# Generated by Django 5.2.7 on 2025-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="description",
            field=models.TextField(default="Nice liveable place"),
            preserve_default=False,
        ),
    ]
